pro_teams <- tibble::tribble(
  ~team, ~pro,
  1L,    "ATL",
  2L,    "BUF",
  3L,    "CHI",
  4L,    "CIN",
  5L,    "CLE",
  6L,    "DAL",
  7L,    "DEN",
  8L,    "DET",
  9L,    "GRB",
  10L,   "TEN",
  11L,   "IND",
  12L,   "KCC",
  13L,   "OAK",
  14L,   "LAR",
  15L,   "MIA",
  16L,   "MIN",
  17L,   "NEG",
  18L,   "NOL",
  19L,   "NYG",
  20L,   "NYJ",
  21L,   "PHI",
  22L,   "ARI",
  23L,   "PIT",
  24L,   "LAC",
  25L,   "SFO",
  26L,   "SEA",
  27L,   "TPA",
  28L,   "WSH",
  29L,   "CAR",
  30L,   "JAX",
  33L,   "BAL",
  34L,   "HOU"
)

usethis::use_data(pro_teams)
